name = "differential_training_v2"
cuda_devices = "1"
plotting_points = 2500
sample_path = "mascons/"
samples = [

    "Itokawa.pk", #For differential training enable the flag in the training section
#    "Bennu.pk", #For differential training enable the flag in the training section

]

[model]
activation = [
    #"Sigmoid",
    # "Abs",
    "Tanh",
]
encoding =  [                           
    # "directional_encoding",
    "direct_encoding",
    # "spherical_coordinates"
]
target_point_samplers = [
    "spherical",          
    #"cubical",
]
sample_domain = [0.0,1.0]
use_acceleration = true
type = " QSGINet" # optional "QSGINet","siren" , "default", "nerf"
hidden_layers = [9]
n_neurons = [100]

[siren]
omega = [30.0]

[integration]
points = 300000
limit_domain=false
domain = [[-1.0,1.0],[-1.0,1.0],[-1.0,1.0]]

[training]
iterations = 10000
batch_sizes = [1000]
lr = 1e-4
losses = [
    # "mse_loss",
    # "normalized_loss",
    # "normalized_sqrt_L1_loss",
    "normalized_L1_loss",
    # "contrastive_loss"
]
visual_loss = false
differential_training=true
validation_points=10000

